@startuml
!include .\\Editor\ObjectEditor.puml
!include .\\Editor\SceneEditor.puml
!include .\\Editor\Tests\ActorModelTest.puml
!include .\\Editor\Tests\AddActorTest.puml
!include .\\Editor\Tests\CameraModelTest.puml
!include .\\Editor\Tests\CameraViewTest.puml
!include .\\Editor\Tests\LightingModelTest.puml
!include .\\Editor\Tests\LightSelectionTest.puml
!include .\\Editor\Tests\LineRendererViewTest.puml
!include .\\Editor\Tests\ModeChangeViewTest.puml
!include .\\Editor\Tests\MotiveStateModelTest.puml
!include .\\Editor\Tests\ObjectSearchViewTest.puml
!include .\\Editor\Tests\ObjectViewTest.puml
!include .\\Editor\Tests\ParticleModelTest.puml
!include .\\Editor\Tests\ParticleViewTest.puml
!include .\\Editor\Tests\PreviewModelTest.puml
!include .\\Editor\Tests\SceneModelTest.puml
!include .\\Editor\Tests\SearchBoxViewTest.puml
!include .\\Editor\Tests\SkyboxModelTest.puml
!include .\\Editor\Tests\SkyboxSelectionTest.puml
!include .\\Editor\Tests\SolidLightModelTest.puml
!include .\\Editor\Tests\SolidLightViewTest.puml
!include .\\Editor\Tests\SpawnLocationTest.puml
!include .\\Editor\Tests\SunLightModelTest.puml
!include .\\Editor\Tests\SunLightViewTest.puml
!include .\\OptiTrack\Scripts\OptitrackRigidBody.puml
!include .\\OptiTrack\Scripts\OptitrackSkeletonAnimator.puml
!include .\\OptiTrack\Scripts\OptitrackStreamingClient.puml
!include .\\Scripts\Models\ActorModel.puml
!include .\\Scripts\Models\AmbientLightingModel.puml
!include .\\Scripts\Models\AvatarConfigurationsToBones.puml
!include .\\Scripts\Models\BackgroundSelectorModel.puml
!include .\\Scripts\Models\CameraModel.puml
!include .\\Scripts\Models\EffectSelectorModel.puml
!include .\\Scripts\Models\LightingModel.puml
!include .\\Scripts\Models\LightingSelectorModel.puml
!include .\\Scripts\Models\LineRendererModel.puml
!include .\\Scripts\Models\Model.puml
!include .\\Scripts\Models\MotiveConnectModel.puml
!include .\\Scripts\Models\MotiveStateModel.puml
!include .\\Scripts\Models\MultiChildModel.puml
!include .\\Scripts\Models\OnChanged.puml
!include .\\Scripts\Models\OnDeleted.puml
!include .\\Scripts\Models\ParticleModel.puml
!include .\\Scripts\Models\PreviewModel.puml
!include .\\Scripts\Models\RigidBodyModel.puml
!include .\\Scripts\Models\SceneModel.puml
!include .\\Scripts\Models\SelectorModel.puml
!include .\\Scripts\Models\SkyboxModel.puml
!include .\\Scripts\Models\SolidColourModel.puml
!include .\\Scripts\Models\SpawnLocation.puml
!include .\\Scripts\Models\SunLightModel.puml
!include .\\Scripts\Models\ThreePointLightModel.puml
!include .\\Scripts\Models\Utils.puml
!include .\\Scripts\Utility\RandomNameGenerator.puml
!include .\\Scripts\Utility\StringUtility.puml
!include .\\Scripts\Utility\WindowUtilityFunctions.puml
!include .\\Scripts\Views\ActorView.puml
!include .\\Scripts\Views\AddActor.puml
!include .\\Scripts\Views\AddRigidBody.puml
!include .\\Scripts\Views\AmbientLightingView.puml
!include .\\Scripts\Views\BackgroundSelector.puml
!include .\\Scripts\Views\CameraView.puml
!include .\\Scripts\Views\ComponentHeader.puml
!include .\\Scripts\Views\EffectSelector.puml
!include .\\Scripts\Views\LightSelection.puml
!include .\\Scripts\Views\LineRendererView.puml
!include .\\Scripts\Views\ModeChangeView.puml
!include .\\Scripts\Views\ObjectSearchView.puml
!include .\\Scripts\Views\ObjectSelectionOption.puml
!include .\\Scripts\Views\ObjectView.puml
!include .\\Scripts\Views\ParticleView.puml
!include .\\Scripts\Views\PreviewView.puml
!include .\\Scripts\Views\RemoveActor.puml
!include .\\Scripts\Views\RigidBodyView.puml
!include .\\Scripts\Views\SceneView.puml
!include .\\Scripts\Views\SearchBoxView.puml
!include .\\Scripts\Views\SkyboxSelection.puml
!include .\\Scripts\Views\SolidLightView.puml
!include .\\Scripts\Views\SunlightView.puml
!include .\\Scripts\Views\ThreePointLightView.puml
!include .\\OptiTrack\Plugins\Managed\NatNetLib\Client.puml
!include .\\OptiTrack\Plugins\Managed\NatNetLib\Native.puml
@enduml
