@startuml
class PreviewModelTest {
    + Setup() : void
    + TearDown() : void
    + PreivewModelCorrectlyCreatesPreviewUI() : IEnumerator
}
PreviewModelTest --> "go" GameObject
PreviewModelTest --> "model" PreviewModel
@enduml
