@startuml
class SunlightView {
    + SunlightView()
}
VisualElement <|-- SunlightView
SunlightView --> "header" ComponentHeader
SunlightView --> "color" ColorField
SunlightView --> "timeOfDay" Slider
@enduml
