@startuml
abstract class MultiChildModel {
    + staleTargets : bool = false
    + emitFrom : string
    + emitFromPrev : string
    + <<override>> Start() : void
    - RecalculateTargets(parentAvatar:GameObject) : void
    - RemoveStaleObjects() : void
    - AddNewObjectsIfDirty() : void
    - UpdateEffects() : void
    + <<override>> OnChanged() : void
    - SpawnEffects(target:Transform) : void
    + <<virtual>> ChildSpawned(target:GameObject) : GameObject
    + <<virtual>> GetAvatar() : GameObject
    + <<virtual>> ChangeBase(go:GameObject) : void
}
class "List`1"<T> {
}
Model <|-- MultiChildModel
MultiChildModel o-> "objectsInScene<GameObject>" "List`1"
MultiChildModel o-> "targets<Transform>" "List`1"
MultiChildModel --> "baseObject" GameObject
MultiChildModel --> "previousBase" GameObject
@enduml
