@startuml
class ThreePointLightModel {
    + angle : float = 90
    - GetByName(name:string) : GameObject
    - DestroyAllWithNameExcept(name:string, exempt:GameObject) : void
    configLight(name:string, c:Color, p:Vector3) : void
    + <<override>> OnChanged() : void
    + <<override>> CreateUI() : VisualElement
}
Model <|-- ThreePointLightModel
ThreePointLightModel o-> "leftLightColour" Color
ThreePointLightModel o-> "rightLightColour" Color
ThreePointLightModel o-> "frontLightColour" Color
@enduml
