@startuml
class LightSelection {
    - label : Label
    - selected : DropdownField
    + LightSelection(choices:List<string>)
}
enum lightingMode {
    solidLight,
    sunlight,
}
VisualElement <|-- LightSelection
LightSelection +-- lightingMode
@enduml
