@startuml
class RigidBodyView {
    - header : ComponentHeader
    - objectField : ObjectSelectionOption
    - skeletonName : TextField
    + RigidBodyView()
}
VisualElement <|-- RigidBodyView
@enduml
