@startuml
class SkyboxSelection {
    - header : ComponentHeader
    - skyboxDropDown : DropdownField
    + SkyboxSelection()
    + {static} getSkyboxRootFolderName() : List<string>
}
VisualElement <|-- SkyboxSelection
@enduml
