@startuml
left to right direction
!include ..\..\..\out_puml\Scripts\Models\PreviewModel.puml
!include ..\..\..\out_puml\Scripts\Models\Model.puml
!include ..\..\..\out_puml\Scripts\Views\PreviewView.puml

PreviewModel -[dotted]-> PreviewView : creates
@enduml
