@startuml
left to right direction
!include ..\..\..\out_puml\Scripts\Models\SceneModel.puml
!include ..\..\..\out_puml\Scripts\Models\Model.puml
!include ..\..\..\out_puml\Scripts\Views\SceneView.puml

SceneModel -[dotted]-> SceneView : creates
@enduml
