@startuml
left to right direction
!include ..\..\..\out_puml\Scripts\Models\SunLightModel.puml
!include ..\..\..\out_puml\Scripts\Models\Model.puml
!include ..\..\..\out_puml\Scripts\Views\SolidLightView.puml

SunLightModel -[dotted]-> SolidLightView : creates
SunLightModel -[dotted]-> Light : sunComponent
@enduml
