@startuml
class AddActorTest {
    window : EditorWindow
    model : AddActor
    addActor : AddActor
    origin : GameObject
    + Setup() : void
    + TearDown() : void
    + ActorIsCreated() : IEnumerator
}
class TestWindow {
}
AddActorTest +-- TestWindow
EditorWindow <|-- TestWindow
@enduml
